baseURL: "https://lilyhe123.github.io"
languageCode: en-us
title: Lily's Blog
theme: PaperMod

pagination:
  pagerSize: 10

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: G-ZGBNCCJMNR

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production
  title: Lily He
  description: "Lily He"
  keywords: [Blog, Portfolio, PaperMod]
  images: ["#"]
  #DateFormat: "Jan 2, 2025"
  defaultTheme: auto
  disableThemeToggle: false

  TocOpen: true

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: false
  ShowRssButtonInSectionTermList: false
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: true
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    favicon: "favicon.ico"
    favicon16x16: "favicon-16x16.png"
    favicon32x32: "favicon-32x32.png"
    apple_touch_icon: "apple-touch-icon.png"

  # home-info mode
  homeInfoParams:
    Title: "Code, Coffee, and Curiosity"
    Content: |
      Share what I'm learning, building, and occasionally stumbling through. 
      Sometimes it’s polished tutorials, sometimes it's just brain-dump.

  socialIcons:
    - name: github
      url: "https://github.com/lilyhe123"
    - name: linkedin
    - name: x
    - name: dev
    - name: rss

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

  analytics:
    google:
      SiteVerificationTag: G-ZGBNCCJMNR

outputs:
  home:
    - HTML
    - RSS
    - JSON

menu:
  main:
    - identifier: search
      name: Search
      url: /search/
      weight: 99
    - identifier: archives
      name: Archive
      url: /archives/
      weight: 2
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 3
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 4

# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    codeFences: true
    # guessSyntax: true
    # lineNos: true
    style: monokai
